# Generated by Django 3.0.5 on 2023-11-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='BNDname',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VRTname',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
