# Generated by Django 3.0.5 on 2023-11-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20231105_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='BNDdesc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VRTdesc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
