# Generated by Django 3.0.5 on 2023-10-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDCTname', models.CharField(max_length=50, verbose_name='Name')),
                ('PDCTdesc', models.TextField(max_length=500, verbose_name='Descriptions')),
                ('PDCTprice', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('PDCTcost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cost')),
                ('PDCTcreated', models.DateTimeField()),
            ],
        ),
    ]
