# Generated by Django 3.0.5 on 2023-10-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PDCTcreated',
            field=models.DateTimeField(verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PDCTname',
            field=models.CharField(max_length=50, verbose_name='Product name'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDCTimage', models.ImageField(upload_to='photo', verbose_name='Image')),
                ('PDCTproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product', verbose_name='Product')),
            ],
        ),
    ]
