# Generated by Django 3.0.5 on 2023-10-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231028_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='PDCTimage',
            field=models.ImageField(upload_to='media', verbose_name='Image'),
        ),
    ]
