# Generated by Django 3.0.5 on 2023-10-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231028_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='PDCTproduct',
            new_name='PDCTIproduct',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='PDCTimage',
        ),
        migrations.AddField(
            model_name='productimage',
            name='PDCTIimage',
            field=models.ImageField(blank=True, null=True, upload_to='product/%y/%m/%d', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATch_cat', models.CharField(max_length=50, verbose_name='Category')),
                ('CATdesc', models.TextField(max_length=500, verbose_name='Description')),
                ('CATimage', models.ImageField(upload_to='category/%y/%m/%d', verbose_name='Category image')),
                ('CATpa_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Parent category')),
            ],
        ),
    ]
