# Generated by Django 3.0.5 on 2023-10-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20231029_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CATch_cat',
            new_name='CATcat',
        ),
    ]
