# Generated by Django 3.0.5 on 2023-10-31 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20231031_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CATnull_cat',
        ),
        migrations.AddField(
            model_name='category',
            name='CATpa_cat',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATpa_cat__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Parent category'),
        ),
    ]
