# Generated by Django 3.0.5 on 2023-10-31 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20231031_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALTRalternative', models.ManyToManyField(related_name='product_alternatives', to='main.Product')),
                ('PALTRproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product alternative',
                'verbose_name_plural': 'Products alternative',
            },
        ),
    ]
