# Generated by Django 3.0.5 on 2023-10-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productalternative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productalternative',
            name='PALTRalternative',
            field=models.ManyToManyField(limit_choices_to={'CATpa_cat__isequal': False}, related_name='product_alternatives', to='main.Product'),
        ),
    ]
