# Generated by Django 3.0.5 on 2023-11-05 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20231102_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PDCTcateg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='category'),
        ),
    ]
