# Generated by Django 3.0.5 on 2023-11-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('main', '0014_product_pdctcateg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PDCTbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Brand'),
        ),
    ]
