# Generated by Django 3.0.5 on 2023-11-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20231105_1535'),
        ('main', '0015_product_pdctbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PDCTbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.Brand'),
        ),
    ]
