# Generated by Django 3.0.5 on 2023-11-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20231105_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PDCTdesc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='descriptions'),
        ),
    ]
