# Generated by Django 3.0.5 on 2023-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20231110_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PDCTimage',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image'),
        ),
    ]
