# Generated by Django 3.0.5 on 2023-11-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product_pdctimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PDCTquant',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantity type'),
        ),
    ]
