# Generated by Django 3.0.5 on 2023-11-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_product_pdctquant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PDCTquant_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantity type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PDCTquant',
            field=models.IntegerField(blank=True, max_length=7, null=True, verbose_name='Quantity'),
        ),
    ]
