# Generated by Django 3.0.5 on 2023-11-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20231110_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CATcat',
        ),
    ]
