# Generated by Django 3.0.5 on 2023-11-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20231110_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATcat', models.CharField(max_length=50, verbose_name='Category')),
                ('CATdesc', models.TextField(max_length=500, verbose_name='Description')),
                ('CATimage', models.ImageField(upload_to='category', verbose_name='Category image')),
                ('CATpa_cat', models.ForeignKey(blank=True, limit_choices_to={'CATpa_cat__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Parent category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='PDCTcateg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='category'),
        ),
    ]
