# Generated by Django 3.0.5 on 2023-11-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20231110_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PDCTimage',
            field=models.ImageField(blank=True, null=True, upload_to='product/%y/%m/%d', verbose_name='Image'),
        ),
    ]
