# Generated by Django 4.2.9 on 2024-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_product_pdctimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='PDCTIimage',
            field=models.ImageField(blank=True, null=True, upload_to='product/<django.db.models.fields.files.ImageFileDescriptor object at 0x000000C287414670>/%y/%m/%d', verbose_name='Image'),
        ),
    ]
