# Generated by Django 4.2.9 on 2024-02-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_productimage_pdctiimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PDCTimage',
            field=models.ImageField(blank=True, null=True, upload_to='product/%y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='PDCTIimage',
            field=models.ImageField(blank=True, null=True, upload_to='product/%y/%m/%d', verbose_name='Image'),
        ),
    ]
