# Generated by Django 4.2.9 on 2024-02-22 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_category_catdsct_image_category_catdsct_prct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATdsct_prct',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount percent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PDCTdsct_prct',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount percent'),
        ),
    ]
